spring.config.import=aws-parameterstore:/cloud-architecture/prod/
spring.cloud.aws.s3.bucket=assignment-soomin0209-files
spring.jpa.hibernate.ddl-auto=validate
management.info.env.enabled=true

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

info.team-name=${TEAM_NAME}